### ISSUE TITLE
AMAS with many genes 

### ISSUE THREAD

**Issue by tomas-fer** [marekborowiec/AMAS#9]
Under certain conditions, AMAS does not work if the number of files to concatenate (or to make summary) exceeds a limit, e.g., 5,000 (the system report 'Argument list too long' error if, e.g., '*.fas' is used to define input files). Is there any chance to input file names using a file with files names specified? Or do you have any other solution? Thanks, Tomas

**Comment by sjswuitchik** [comment]
I am also running into this issue in my analysis - following in hopes of a solution!.

**Comment by marekborowiec** [comment]
The issue most likely stems from your system having a low limit on number of characters that can be processed as a command line argument. You can see what number of characters you're limited to by running `getconf ARG_MAX`.

There are three potential solutions I can think of:
1. Split your alignments into several directories, then concatenate them in turn and finally concatenate those intermediate files together
2. Use a computer where the `ARG_MAX` limit is set to a higher number.
3. [Increase your `ARG_MAX` limit](https://stackoverflow.com/questions/14387344/is-it-possible-to-increase-the-maximum-number-of-characters-that-ksh-variable-ac). This may require updating your Linux system.

Note that using `find` and `xargs`, as suggested [here](https://stackoverflow.com/questions/11289551/argument-list-too-long-error-for-rm-cp-mv-commands), will not help you. This is because this solution processes one file at a time, which would mean concatenating one file at a time.

**Comment by sjswuitchik** [comment]
Turns out it was an issue on our HPC with CentOS7 - unfortunately wasn't able to overcome the arg max issue (even when set to unlimited) & had to use a different software. Thank you for your suggestions though!
